Array

In [14]:
import numpy as np

# creating 1-D array
a=np.array([2,3,4])
print(a)
print(type(a))

[2 3 4]
<class 'numpy.ndarray'>


In [15]:
# simplified
x=[5,6,7,8]
y=np.array(x)
print(y)
print(type(a))

[5 6 7 8]
<class 'numpy.ndarray'>


## l=[]
for i in range(1,5):
    int_1 = int(input("Enter"))
    l.append(int_1)
print(np.array(l))

In [23]:
# dimensions
# 1-D arrays
a=np.array([1,2,3,4,5])
# 2-D arrays
b=np.array([[1,2,3,4,5],[5,6,7,8,9]])
# 3-D arrays
c=np.array([[[1,2,3,4,5],[6,7,8,9,0],[1,1,1,1,1]]])
# to see dimensions , count brackets from left to right
print("array a :")
print(a)
print(a.ndim)
print("array b :")
print(b)
print(b.ndim)
print("array c :")
print(c)
print(c.ndim)

array a :
[1 2 3 4 5]
1
array b :
[[1 2 3 4 5]
 [5 6 7 8 9]]
2
array c :
[[[1 2 3 4 5]
  [6 7 8 9 0]
  [1 1 1 1 1]]]
3


In [24]:
# multidim array
arn=np.array([1,2,3,4],ndmin=10)
print(arn)
print(arn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
10
