In [1]:
import numpy as np
print('Imported')

Imported


# zeros

In [2]:
#  0  array
# 1-D array
ar_zero = np.zeros(4)
print(ar_zero)
# 3x4 array
ar_zero1 = np.zeros((3,4))
print(ar_zero1)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# ones

In [3]:
# 1 array
# 1-D array
ar_one=np.ones(4)
print(ar_one)
# 3x4 array
ar_one1 = np.ones((3,4))
print(ar_one1)

[1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


# Empty

In [4]:
ar_emp = np.empty(4)
print(ar_emp)

# [1. 1. 1. 1.] is output because previous array memory comes in empty array

[1. 1. 1. 1.]


# arange

In [5]:
ar_rr=np.arange(4)
print(ar_rr)

[0 1 2 3]


# Identity matrix

In [6]:
# rows = columns
ar_dig= np.eye(4)
print(ar_dig)
# rows != columns
ar_dig= np.eye(4,7)
print(ar_dig)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]]


# space

In [7]:
# equal space saperation
ar_sp=np.linspace(0,20,num=5)
print(ar_sp)

[ 0.  5. 10. 15. 20.]
