In [1]:
import numpy as np
print('imported')

imported


# Random Functions

In [2]:
# 1-D array
# rand = 0 < number < 1
var=np.random.rand(4)
print(var)
# 3x5-D array
var1=np.random.rand(3,5)
print(var1)

[0.06899438 0.42728097 0.97403033 0.47192184]
[[0.65679227 0.88786087 0.42004944 0.97893787 0.33308374]
 [0.03147035 0.18874512 0.33447598 0.20569979 0.67963961]
 [0.70681683 0.40597633 0.80855663 0.10850619 0.57480311]]


In [3]:
# randn = numbers closed to 0 ( +ve or -ve)
var2=np.random.randn(5)
print(var2)

[-0.982995    0.16230178  0.25215063  0.3704917  -0.63891727]


In [4]:
# ranf = for [0,1)
# simply includes 0 but not 1
var3 = np.random.ranf(5)
print(var3)

[0.29893621 0.79017843 0.84975792 0.16584    0.49877594]


In [5]:
# randint : random between given two numbers
var4 = np.random.randint(0,15,7)
# (min,max,numberofvalues)
print(var4)

[ 1  2 10 11  2  4 11]
