for more
https://numpy.org/doc/stable/user/basics.types.html

# Numpy datatypes

In [1]:
import numpy as np

In [2]:
var=np.array([123,234,322,3,4])
print('Data type : ',var.dtype)

Data type :  int64


In [3]:
var1=np.array([1.2,2.3,4.5])
print('Data type : ',var1.dtype)

Data type :  float64


In [4]:
var2=np.array([1.2,2.3,4.5,2,3,4,5])
print('Data type : ',var2.dtype)
print(var2)

Data type :  float64
[1.2 2.3 4.5 2.  3.  4.  5. ]


In [5]:
var3=np.array([1.2,2.3,4.5,'s','d','f','g'])
print('Data type : ',var3.dtype)

Data type :  <U32


* typecasting

In [6]:
x=np.array([1,2,3,4,5])
print('data type of x : ',x.dtype)
print(x)
x1=np.array([1,2,3,4,5],dtype=np.int8)
print('data type of x1 : ',x1.dtype)
print(x1)

data type of x :  int64
[1 2 3 4 5]
data type of x1 :  int8
[1 2 3 4 5]


In [7]:
x=np.array([1,2,3,4,5])
print('data type of x : ',x.dtype)
print(x)
x1=np.array([1,2,3,4,5],dtype="f")
print('data type of x1 : ',x1.dtype)
print(x1)

data type of x :  int64
[1 2 3 4 5]
data type of x1 :  float32
[1. 2. 3. 4. 5.]


In [8]:
x=np.array([1,2,3,4,5])
# passing as a function
new = np.float32(x)
# converting back again
new_1 = np.int_(new)
print(x)
print('data type of x : ',x.dtype)
print('data type of x : ',new.dtype)
print('data type of x : ',new_1.dtype)

[1 2 3 4 5]
data type of x :  int64
data type of x :  float32
data type of x :  int64


In [9]:
x3=np.array([1,2,3,4,5])
new_2=x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4 5]
[1 2 3 4 5]
