In [1]:
import numpy as np

# Arethmatic operations

addition

In [2]:
# 1 - d
var = np.array([1,2,3,4,5])
varadd= var + 3
print(varadd)

# by function
var = np.array([1,2,3,4,5])
varadd= np.add(var,3)
print(varadd)

# for 2
var = np.array([1,2,3,4,5])
var0 = np.array([1,1,1,1,1])
varadd1=var+var0
print(varadd1)

# by function
var = np.array([1,2,3,4,5])
var0 = np.array([1,1,1,1,1])
varadd1func=np.add(var,var0)
print(varadd1func)

[4 5 6 7 8]
[4 5 6 7 8]
[2 3 4 5 6]
[2 3 4 5 6]


subtraction

In [3]:
# 1 - d
var = np.array([1,2,3,4,5])
varsub= var - 3
print(varsub)

# 1 - d
var = np.array([1,2,3,4,5])
varsub= np.subtract(var,3)
print(varsub)

# for 2
var = np.array([1,2,3,4,5])
var0 = np.array([1,1,1,1,1])
varsub1= var-var0
print(varsub1)

var = np.array([1,2,3,4,5])
var0 = np.array([1,1,1,1,1])
varsub1= np.subtract(var,var0)
print(varsub1)

[-2 -1  0  1  2]
[-2 -1  0  1  2]
[0 1 2 3 4]
[0 1 2 3 4]


multiply

In [4]:
# 1 - d
var = np.array([1,2,3,4,5])
varmul= var * 3
print(varmul)

# 1 - d
var = np.array([1,2,3,4,5])
varmul= np.multiply(var,3)
print(varmul)

# for 2
var = np.array([1,2,3,4,5])
var0 = np.array([1,3,11,13,12])
varmul1= var*var0
print(varmul1)

var = np.array([1,2,3,4,5])
var0 = np.array([1,3,11,13,12])
varmul1= np.multiply(var,var0)
print(varmul1)

[ 3  6  9 12 15]
[ 3  6  9 12 15]
[ 1  6 33 52 60]
[ 1  6 33 52 60]


divide

In [5]:
# 1 - d
var = np.array([1,2,3,4,5])
vardiv= var / 3
print(vardiv)

# 1 - d
var = np.array([1,2,3,4,5])
vardiv= np.divide(var,3)
print(vardiv)

# for 2
var = np.array([1,2,3,4,5])
var0 = np.array([1,1,1,1,1])
vardiv1= var/var0
print(vardiv1)

# for 2
var = np.array([1,2,3,4,5])
var0 = np.array([1,1,1,1,1])
vardiv1= np.divide(var,var0)
print(vardiv1)

[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[0.33333333 0.66666667 1.         1.33333333 1.66666667]
[1. 2. 3. 4. 5.]
[1. 2. 3. 4. 5.]


Modulus

In [6]:
# 1 - d
var = np.array([1,2,3,4,5])
varmod= var % 3
print(varmod)

# 1 - d
var = np.array([1,2,3,4,5])
varmod= np.mod(var,3)
print(varmod)

# for 2
var = np.array([1,2,3,4,5])
var0 = np.array([1,1,1,1,1])
varmod1= var%var0
print(varmod1)

# for 2
var = np.array([1,2,3,4,5])
var0 = np.array([1,1,1,1,1])
varmod1= np.mod(var,var0)
print(varmod1)

[1 2 0 1 2]
[1 2 0 1 2]
[0 0 0 0 0]
[0 0 0 0 0]


power

In [7]:
# 1 - d
var = np.array([1,2,3,4,5])
varpow= var ** 3
print(varpow)

# 1 - d
var = np.array([1,2,3,4,5])
varpow= np.power(var,3)
print(varpow)

# for 2
var = np.array([1,2,3,4,5])
var0 = np.array([1,1,1,1,1])
varpow1= var**var0
print(varpow1)

# for 2
var = np.array([1,2,3,4,5])
var0 = np.array([1,1,1,1,1])
varpow1= np.power(var,var0)
print(varpow1)

[  1   8  27  64 125]
[  1   8  27  64 125]
[1 2 3 4 5]
[1 2 3 4 5]


reciprocal

In [8]:
# 1 - d
var = np.array([1,2,3,4,5])
rec= 1/var
print(rec)

# 1 - d
var1 = np.array([1,2,3,4,5])
rec1= np.reciprocal(var)
print(rec)

[1.         0.5        0.33333333 0.25       0.2       ]
[1.         0.5        0.33333333 0.25       0.2       ]


* 2-D array

In [9]:
# 1 - d
var = np.array([[1,2,3,4,5],[6,7,8,9,9]])
varsub= var - 3
print(varsub)
print("\n")
# 1 - d
var = np.array([[1,2,3,4,5],[5,4,4,4,4]])
varsub= np.subtract(var,3)
print(varsub)
print("\n")

# for 2
var = np.array([[1,2,3,4,5],[9,8,7,65,4]])
var0 = np.array([[1,1,1,1,1],[7,7,7,7,7]])
varsub1= var-var0
print(varsub1)
print("\n")

var = np.array([[1,2,3,4,5],[9,8,7,65,4]])
var0 = np.array([[1,1,1,1,1],[7,7,7,7,7]])
varsub1= np.subtract(var,var0)
print(varsub1)
print("\n")


[[-2 -1  0  1  2]
 [ 3  4  5  6  6]]


[[-2 -1  0  1  2]
 [ 2  1  1  1  1]]


[[ 0  1  2  3  4]
 [ 2  1  0 58 -3]]


[[ 0  1  2  3  4]
 [ 2  1  0 58 -3]]




# now you can do it next by yourself :)

# It works as a matrix arethmatics