In [1]:
import numpy as np

# Some basic functions in Numpy

* 1 - D array

In [2]:
a=np.array([1,2,3,4,5])

print(a)

print('minimum;')
print(np.min(a))
print('maximum :')
print(np.max(a))

print('the position of minimum element :')
print(np.argmin(a))
print('the position of maximum element :')
print(np.argmax(a))

[1 2 3 4 5]
minimum;
1
maximum :
5
the position of minimum element :
0
the position of maximum element :
4


* 2-D array

In [3]:
b=np.array([[1,2,3,4,5],[9,8,7,6,5]])
print(b)
print(b.ndim)

print('minimum;')
print(np.min(b,1))
print('maximum :')
print(np.max(b,1))

[[1 2 3 4 5]
 [9 8 7 6 5]]
2
minimum;
[1 5]
maximum :
[5 9]


* square root

In [4]:
print('square root :')
print(np.sqrt(a))
print(np.sqrt(b))

square root :
[1.         1.41421356 1.73205081 2.         2.23606798]
[[1.         1.41421356 1.73205081 2.         2.23606798]
 [3.         2.82842712 2.64575131 2.44948974 2.23606798]]


* trignometry

In [5]:
c=np.array([0,30,45,60,90])
print(np.sin(c))
print(np.cos(c))
print(np.tan(c))

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041]


* cummelity sum

In [6]:
print(np.cumsum(c))
# let c= [0,30,45,60,90]
# so 
# let element 0 = 0
# element 1 = element 1 + element 0
# 0+30=30
# element 1 = element 2 + element 1
# 30+45=75
# 75+60=135
# 135+90=225

[  0  30  75 135 225]
