In [1]:
import numpy as np

# Shape

In [2]:
a=np.array([[1,2],[2,3]])
print(a)
print("Shape is :",a.shape)

[[1 2]
 [2 3]]
Shape is : (2, 2)


In [3]:
b=np.array([1,2,3,4],ndmin=7)
print(b)
print("Shape is :",b.shape)

[[[[[[[1 2 3 4]]]]]]]
Shape is : (1, 1, 1, 1, 1, 1, 4)


* dimension conversion

In [4]:
c=np.array([1,2,3,4,5,6])
x=c.reshape(3,2)
print('the dimension of c is :',c.ndim)
print(c)
print('the dimension of x is :',x.ndim)
print(x)
# NOTE = ROWs x COLUMNs = Number of total elements
print('\nreshaping ...')
y=x.reshape(-1)
print(y)
print(y.ndim)

the dimension of c is : 1
[1 2 3 4 5 6]
the dimension of x is : 2
[[1 2]
 [3 4]
 [5 6]]

reshaping ...
[1 2 3 4 5 6]
1
