In [1]:
import numpy as np

# broadcasting

In [2]:
a=np.array([1,2,3])
b=np.array([5,4,6])
print(a+b)

[6 6 9]


* broadcasting : following the rules
    * 1 : the 2 matrix dimensions should be same

In [3]:
a=np.array([1,2,3])
print(a)
print(a.shape)
b=np.array([[1],[2],[3]])
print('\n',b)
print(b.shape)
print('\n')
print(a+b)

[1 2 3]
(3,)

 [[1]
 [2]
 [3]]
(3, 1)


[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [4]:
# [ 1  2  3 ]+[1]
#             [2]
#             [3]
#   1+1    2+1   3+1   
#   1+2    2+2   3+2
#   1+3    2+3   3+3

In [5]:
c=np.array([[1],[2]])
print(c)
print('\n')
print(c.shape)
d=np.array([[1,2,3],[1,2,3]])
print(d)
print(d.shape)
print('\n')
print(c+d)

[[1]
 [2]]


(2, 1)
[[1 2 3]
 [1 2 3]]
(2, 3)


[[2 3 4]
 [3 4 5]]


In [6]:
# 2x1  2x3 
# 2==2
# max = 3
# result = 2x3

# simply follow the rules of matrix arethmatics