In [1]:
import numpy as np

# Itration

In [2]:
a=np.array([1,2,3,4,5,6,7,8,9])
print(a)

[1 2 3 4 5 6 7 8 9]


In [3]:
for i in a:
    print(i)

1
2
3
4
5
6
7
8
9


In [4]:
b=np.array([[1,2,3,4,5],[5,4,3,2,1]])
print(b)

[[1 2 3 4 5]
 [5 4 3 2 1]]


In [5]:
for j in b:
    print(j)

[1 2 3 4 5]
[5 4 3 2 1]


In [6]:
for k in b:
    for l in k:
        print(l)

1
2
3
4
5
5
4
3
2
1


In [7]:
c=np.array([[[1,2,3,4,5],[1,2,3,4,5],[1,2,2,2,2]]])
print(c)
print(c.ndim)

[[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 2 2 2]]]
3


In [8]:
for i in c:
    for j in i:
        for k in j:
            print(k)

1
2
3
4
5
1
2
3
4
5
1
2
2
2
2


* less for loop

In [9]:
print("without function\n")
for i in c:
    for j in i:
        for k in j:
            print(k)
print("\n")
print("direct function\n")
for i in np.nditer(c):
    print(i)

without function

1
2
3
4
5
1
2
3
4
5
1
2
2
2
2


direct function

1
2
3
4
5
1
2
3
4
5
1
2
2
2
2


In [10]:
for i in np.nditer(c,flags=['buffered'],op_dtypes=["S"]):
    print(i)
# changing datatypes

b'1'
b'2'
b'3'
b'4'
b'5'
b'1'
b'2'
b'3'
b'4'
b'5'
b'1'
b'2'
b'2'
b'2'
b'2'


In [11]:
for i,d in np.ndenumerate(c):
    print(i,d)
# indexing valuewise

(0, 0, 0) 1
(0, 0, 1) 2
(0, 0, 2) 3
(0, 0, 3) 4
(0, 0, 4) 5
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
(0, 1, 4) 5
(0, 2, 0) 1
(0, 2, 1) 2
(0, 2, 2) 2
(0, 2, 3) 2
(0, 2, 4) 2
