In [1]:
import numpy as np

# array operations

# Merging

* number of elements should same

* !-D array

In [2]:
a=np.array([1,2,3,4])
b=np.array([4,3,2,1])
ar=np.concatenate((a,b))
print(a)
print(b)
print(ar)

[1 2 3 4]
[4 3 2 1]
[1 2 3 4 4 3 2 1]


* 2-D array

In [3]:
c = np.array([[1, 2], [3, 2]])
d = np.array([[2, 3], [4, 5]])
ar1 = np.concatenate((c, d), axis=1)
ar2 = np.concatenate((c, d), axis=0)
print(c)
print(d)
print(ar1)
print(ar2)

[[1 2]
 [3 2]]
[[2 3]
 [4 5]]
[[1 2 2 3]
 [3 2 4 5]]
[[1 2]
 [3 2]
 [2 3]
 [4 5]]


In [4]:
ar3=np.stack((a,b),axis=1)
print(ar3)

[[1 4]
 [2 3]
 [3 2]
 [4 1]]


In [5]:
ar4=np.stack((c,d),axis=1)
print(ar4)

[[[1 2]
  [2 3]]

 [[3 2]
  [4 5]]]


In [6]:
# along row
ar3=np.hstack((a,b))
print(ar3)

[1 2 3 4 4 3 2 1]


In [7]:
# along colums
ar3=np.vstack((a,b))
print(ar3)

[[1 2 3 4]
 [4 3 2 1]]


In [8]:
# along height
ar3=np.dstack((a,b))
print(ar3)

[[[1 4]
  [2 3]
  [3 2]
  [4 1]]]


# Split array

In [9]:
p=np.array([1,2,3,4,5,6,7,8])
print(p)
ar=np.array_split(a,2)
print(ar)
ar2=np.array_split(a,4)
print(ar2)

[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4])]
[array([1]), array([2]), array([3]), array([4])]


In [10]:
print(ar2[0])

[1]


In [11]:
b=np.array([[1,2],[3,4],[5,6]])
print(b)
ar4=np.array_split(b,3)
print(ar4)

[[1 2]
 [3 4]
 [5 6]]
[array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]


In [12]:
ar5=np.array_split(b,3,axis=1)
print(ar5)

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]]), array([], shape=(3, 0), dtype=int64)]
