In [1]:
import numpy as np

# functions in numpy

* search

In [2]:
a=np.array([6,5,4,7,6,5,4,6])
print(a)
search=np.where(a == 5)
print(search)
chk=np.where(a%2==0)
print(chk)

[6 5 4 7 6 5 4 6]
(array([1, 5]),)
(array([0, 2, 4, 6, 7]),)


In [3]:
xa=np.array([1,2,3,4,5,6,7])
print(xa)
search=np.where(xa == 5)
print(search)
# by binary search method

[1 2 3 4 5 6 7]
(array([4]),)


* search sorted array : binary search array

* Sorting

In [4]:
# a is an unsorted array
a=np.array([6,5,4,7,6,5,4,6])
print(a)
a1=np.sort(a)
print(a1)

[6 5 4 7 6 5 4 6]
[4 4 5 5 6 6 6 7]


In [5]:
b=np.array([[2,4,3],[5,4,6],[8,7,8]])
print(b)
a1=np.sort(b)
print(a1)

[[2 4 3]
 [5 4 6]
 [8 7 8]]
[[2 3 4]
 [4 5 6]
 [7 8 8]]


In [6]:
c=np.array(['a','s','d','g'])
print(c)
a1=np.sort(c)
print(a1)

['a' 's' 'd' 'g']
['a' 'd' 'g' 's']


for different sorting algorithms in c :
https://github.com/AYUSHKHAIRE/data-structures-in-c/blob/main/data%20structres%20in%20C/data_structures.c

* Filter

In [7]:
c1=np.array(['a','s','d','g'])
f=[True,False,False,False]
nw_arr=c1[f]
print(nw_arr)

['a']
