In [1]:
import numpy as np

# Insert

In [2]:
a=np.array([1,2,3,4])
print(a)
print(type(a))

[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
b=np.insert(a,2,40)
print(b)

[ 1  2 40  3  4]


In [4]:
c=np.insert(a,2,4.4530)
print(c)

[1 2 4 3 4]


In [5]:
d=np.array([[1,2],[3,4]])
print(d)

[[1 2]
 [3 4]]


In [6]:
e=np.insert(d,2,4,axis=0)
print(e)

[[1 2]
 [3 4]
 [4 4]]


In [7]:
f=np.insert(d,2,4,axis=1)
print(f)

[[1 2 4]
 [3 4 4]]


In [8]:
g=np.insert(d,2,[22,23],axis=0)
print(g)

[[ 1  2]
 [ 3  4]
 [22 23]]


In [9]:
h=np.insert(d,2,[22,23],axis=1)
print(h)

[[ 1  2 22]
 [ 3  4 23]]


# Delete

In [10]:
h=np.array([2,4,5,7])
print(h)

[2 4 5 7]


In [11]:
i=np.delete(h,2)
print(i)

[2 4 7]
