In [1]:
import numpy as np

# Matrix

In [2]:
a=np.matrix([[1,2,3],[1,2,3]])
print(a)
print(type(a))

[[1 2 3]
 [1 2 3]]
<class 'numpy.matrix'>


In [3]:
b=np.array([[1,2,3],[1,2,3]])
print(b)
print(type(b))

[[1 2 3]
 [1 2 3]]
<class 'numpy.ndarray'>


In [4]:
c=np.matrix([[2,3,4],[5,6,4]])
print(c)
print(type(c))


[[2 3 4]
 [5 6 4]]
<class 'numpy.matrix'>


In [5]:
print(a+c)
print("\n")
print(a-c)
print("\n")

[[3 5 7]
 [6 8 7]]


[[-1 -1 -1]
 [-4 -4 -1]]




In [6]:
e=np.array([[1,2,3],[4,5,6],[7,8,9]])
f=np.array([[3,2,1],[6,5,4],[9,8,7]])
print(e)
print('')
print(f)
print('')
print(e.dot(f))

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[3 2 1]
 [6 5 4]
 [9 8 7]]

[[ 42  36  30]
 [ 96  81  66]
 [150 126 102]]


In [7]:
print(b*b)

[[1 4 9]
 [1 4 9]]


In [8]:
g=np.matrix([[2,3,4],[5,5,7],[8,6,5]])
print(g)
print('')

t=np.transpose(g)
print(t)
print('or')
print(g.T)
print('')

# swapxces
sa=np.swapaxes(g,0,1)
print(sa)
print('')

# inverse
i=np.linalg.inv(g)
print(i)
print('')

# power
p=np.linalg.matrix_power(g,0)
print(p)
print('')

p3=np.linalg.matrix_power(g,3)
print(p3)
print('')

p_3=np.linalg.matrix_power(g,-3)
print(p_3)
print('')

# determinint
d=np.linalg.det(g)
print(d)
print('')

[[2 3 4]
 [5 5 7]
 [8 6 5]]

[[2 5 8]
 [3 5 6]
 [4 7 5]]
or
[[2 5 8]
 [3 5 6]
 [4 7 5]]

[[2 5 8]
 [3 5 6]
 [4 7 5]]

[[-0.89473684  0.47368421  0.05263158]
 [ 1.63157895 -1.15789474  0.31578947]
 [-0.52631579  0.63157895 -0.26315789]]

[[1 0 0]
 [0 1 0]
 [0 0 1]]

[[ 719  672  764]
 [1312 1223 1388]
 [1384 1272 1427]]

[[-2.96180201  1.87549205 -0.23851873]
 [ 7.11007435 -4.57253244  0.64090975]
 [-3.46522817  2.25688876 -0.33926228]]

18.999999999999996



 # Congratulations !!
 Certificate of completion
 to,
 Dear candidate ,
 Congratulations for completing Numpy successfully